name: ci

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci.yml
      - docs/**
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - docs/**

jobs:
  retype-build:
    name: Retype build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          branch: main
          directory: public
          update-branch: true
